-- begin TOTALFIELD_ORDER_PRODUCT_ITEM
alter table TOTALFIELD_ORDER_PRODUCT_ITEM add constraint FK_TOTALFIELD_ORDER_PRODUCT_ITEM_PRODUCT foreign key (PRODUCT_ID) references TOTALFIELD_PRODUCT(ID)^
alter table TOTALFIELD_ORDER_PRODUCT_ITEM add constraint FK_TOTALFIELD_ORDER_PRODUCT_ITEM_ORDER foreign key (ORDER_ID) references TOTALFIELD_ORDER(ID)^
create index IDX_TOTALFIELD_ORDER_PRODUCT_ITEM_ORDER on TOTALFIELD_ORDER_PRODUCT_ITEM (ORDER_ID)^
create index IDX_TOTALFIELD_ORDER_PRODUCT_ITEM_PRODUCT on TOTALFIELD_ORDER_PRODUCT_ITEM (PRODUCT_ID)^
-- end TOTALFIELD_ORDER_PRODUCT_ITEM
-- begin TOTALFIELD_ORDER_SERVICE_ITEM
alter table TOTALFIELD_ORDER_SERVICE_ITEM add constraint FK_TOTALFIELD_ORDER_SERVICE_ITEM_SERVICE foreign key (SERVICE_ID) references TOTALFIELD_SERVICE(ID)^
alter table TOTALFIELD_ORDER_SERVICE_ITEM add constraint FK_TOTALFIELD_ORDER_SERVICE_ITEM_ORDER foreign key (ORDER_ID) references TOTALFIELD_ORDER(ID)^
create index IDX_TOTALFIELD_ORDER_SERVICE_ITEM_ORDER on TOTALFIELD_ORDER_SERVICE_ITEM (ORDER_ID)^
create index IDX_TOTALFIELD_ORDER_SERVICE_ITEM_SERVICE on TOTALFIELD_ORDER_SERVICE_ITEM (SERVICE_ID)^
-- end TOTALFIELD_ORDER_SERVICE_ITEM
